---EL ARCHIVO RESOURCE ES BASICAMENTE EL ENCARGADO DE DECIRLE AL SERVIDOR
--QUE ESTO ES UN RECURSO Y POR TANTO TIENE UN SCRIPT Y...POR TANTO... DEBRA DE CARGARLO
--EN EL RESOURCE SE COLOCA TODO LO QUE SE DEBA DE CARGAR
client_script "client.lua" 
